### ISSUE TITLE
[1.18.2] Crashing in Server

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#22]
Noticed this crash log in AQM2's official server. Can't really give much details as it wasn't reported to me, just saw it happened a few times in the crash reports folder.

https://pastebin.com/n1tSyCLh

**Comment by spoorn** [comment]
Interesting, let's break this down:

1. A player opened a myLoot chest -> `ChestBlock.onUse`
2. This triggers loot to be generated for the chest, and it looks like the server has `enableRandomSeedLootPerPlayer = true` so it generates new random loot for the player -> `generateRandomLoot`
3. One of the items that was generated is an Explorer Map -> `ExplorationMapLootFunction`
4. This triggers a locate command for a Jigsaw structure -> `ChunkGenerator.locateStructure` and `JigsawFeature.method_38676`
5. This then triggers generation of the structure and the chunk(s) it's in -> `StructurePoolBasedGenerator.generate`
6. This generation takes too long and it triggers Watchdog to timeout (default 60 seconds, or whatever you set __max-tick-time__ to in server.properties) -> `java.lang.Error: Watchdog`

It looks like there have been other reports of Explorer Maps causing timeouts, but that's when Optifine or `generate-structures=false` in server.properties: https://bugs.mojang.com/browse/MC-126244, https://bugs.mojang.com/browse/MC-130449

Do you know if either of those cases apply to you?

Step (2) where myLoot generates new random loot for the player is the same code as vanilla, and invoked the same way - when the player opens the inventory that should generate loot i.e. the ChestBlock.  

I'm thinking some structure, or the worldgen for the chunks the structure is in is taking too long to generate causing the timeout.

Any chance you could fetch the __world seed__ and __modpack version__ you're using so I can see if I can reproduce it?

**Comment by spoorn** [comment]
I actually found a similar crash report in my own server for this as well, only happened one time for me though.  It's the same issue where it generates loot one of which is the Explorer Map, and triggers structure /locate which times out.

In my case though, this is purely the vanilla `checkLootInteraction` (MyLootChestBlockEntity just calls the vanilla `checkLootInteraction`), where it's the very first time the loot is generated for the ChestBlock, so it doesn't run through the myLoot random loot generation per player.  This makes me highly suspect it's because Explorer Maps trigger locate and structure/chunk generation which can be especially slow in heavily modded worlds.  I'll try to reproduce it some more

[crash-reports_crash-2022-07-19_10.42.44-server.txt](https://github.com/spoorn/myLoot/files/9174846/crash-reports_crash-2022-07-19_10.42.44-server.txt)

**Comment by spoorn** [comment]
Do you have terralith installed?

**Comment by spoorn** [comment]
I was able to reproduce this and found out the Explorer Map turns into a Terralith Traveler's Map which has known issues with timing out: https://www.curseforge.com/minecraft/mc-mods/terralith?comment=918

![image](https://user-images.githubusercontent.com/12925899/180626925-a004c965-0553-4198-9e85-882d7c9d9eec.png)

**Comment by spoorn** [comment]
@itsdinkd 

If it helps, I have a mod that allows you to trigger commands on server startup which you could add those `/scoreboard` commands to: https://www.curseforge.com/minecraft/mc-mods/starter-items

I needed this for my own modpack

**Comment by itsdinkd** [comment]
Shiiiiiet i never saw this! im getting a lot of these crashes lately. nice okay I'm going to add that scoreboard now.

**Comment by itsdinkd** [comment]
> Shiiiiiet i never saw this! im getting a lot of these crashes lately. nice okay I'm going to add that scoreboard now.

**Comment by itsdinkd** [comment]
also @spoorn I have several different watchdog crashes that involve MyLoot. CAn I send them your way?

**Comment by spoorn** [comment]
> also @spoorn I have several different watchdog crashes that involve MyLoot. CAn I send them your way?

sure

**Comment by itsdinkd** [comment]
> > also @spoorn I have several different watchdog crashes that involve MyLoot. CAn I send them your way?
> 
> sure

https://mclo.gs/GKCLiWX
https://mclo.gs/moRAP4h
https://mclo.gs/MLgN9Tz
